name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Generate package
        run: python -m build

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: password-generator-package
          path: dist/
